spring.application.name=wallet-service


spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallet_db}
spring.datasource.username=${DB_USER:wallet_user}
spring.datasource.password=${DB_PASSWORD:wallet_pass}
server.port=${APP_PORT:8080}

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml